apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.am.pod_name | default "forgerock-access-manager" | quote }}
  namespace: {{ .Values.secrets.namespace | quote }}
data:
  {{- (.Files.Glob "am_config/properties").AsConfig | nindent 2 }}
  {{- (.Files.Glob "am_config/auth_trees/*").AsConfig | nindent 2 }}
  {{- (.Files.Glob "am_config/amster/*").AsConfig | nindent 2 }}
