---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.idm.service_name | quote }}
  namespace: {{ .Values.idm.namespace }}
  labels:
    app: {{ .Values.idm.pod_name | quote }}
    release: {{ .Values.idm.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.idm.pod_name | quote }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.idm.service_name }}-lb"
  namespace: {{ .Values.idm.namespace }}
  labels:
    app: {{ .Values.idm.pod_name | quote }}
    release: {{ .Values.idm.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.idm.pod_name | quote }}
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
